"""init_error_show_db

迁移 ID: f93a91fba37c
父迁移:
创建时间: 2025-08-08 14:13:53.978304

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "f93a91fba37c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_error_show_tracelog",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bot", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("exception", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_error_show_tracelog")),
        info={"bind_key": "nonebot_plugin_error_show"},
    )
    op.create_table(
        "nonebot_plugin_error_show_tracesub",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.String(), nullable=False),
        sa.Column("adapter", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_error_show_tracesub")),
        info={"bind_key": "nonebot_plugin_error_show"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_error_show_tracesub")
    op.drop_table("nonebot_plugin_error_show_tracelog")
    # ### end Alembic commands ###
